<a href="https://colab.research.google.com/github/James-Arogo/Parrot/blob/master/Dataframse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd

df=pd.DataFrame({'Population':[53.897,67.783,337.891,623.004,111.673,12.784,197.761],'GDP':[5467253,7834523,435134,5466237,900756,546731,562828],'Surface Area':[433556,233145,673442,123424,546112,527117,197339],'MDI':[0.949,0.873,0.994,0.956,0.779,0.903,0.998],'Continent':['South America','Europe','Asia','Africa','North America','Australia','Middle East']},columns=['Population','GDP','Surface Area','MDI','Continent'])
print(df)


   Population      GDP  Surface Area    MDI      Continent
0      53.897  5467253        433556  0.949  South America
1      67.783  7834523        233145  0.873         Europe
2     337.891   435134        673442  0.994           Asia
3     623.004  5466237        123424  0.956         Africa
4     111.673   900756        546112  0.779  North America
5      12.784   546731        527117  0.903      Australia
6     197.761   562828        197339  0.998    Middle East


In [ ]:
df.index=['South America','Europe','Asia','Africa','North America','Australia','Middle East']
df

Population      GDP  Surface Area    MDI      Continent
South America      53.897  5467253        433556  0.949  South America
Europe             67.783  7834523        233145  0.873         Europe
Asia              337.891   435134        673442  0.994           Asia
Africa            623.004  5466237        123424  0.956         Africa
North America     111.673   900756        546112  0.779  North America
Australia          12.784   546731        527117  0.903      Australia
Middle East       197.761   562828        197339  0.998    Middle East

In [4]:
from sklearn.datasets import load_iris
Iris=load_iris()
x=Iris.data
y=Iris.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
col_names = Iris.feature_names
print(col_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
