<a href="https://colab.research.google.com/github/James-Arogo/Parrot/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.getsizeof(10**100)
np.dtype(float).itemsize

8

In [4]:
np.dtype(int).itemsize

8

In [5]:
np.dtype(float).base

dtype('float64')

In [9]:
np.dtype(np.int32).itemsize

4

In [10]:
np.array([1]).nbytes

8

In [30]:
l=list(np.arange(100000))


In [25]:
a=np.arange(100000)

In [27]:
a=np.arange(100000)


In [28]:
%time np.sum(a**2)

CPU times: user 1.39 ms, sys: 38 µs, total: 1.43 ms
Wall time: 1.06 ms


np.int64(333328333350000)

In [31]:
%time np.sum([x**2 for x in l])

CPU times: user 27.7 ms, sys: 510 µs, total: 28.2 ms
Wall time: 29.5 ms


np.int64(333328333350000)

In [32]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(1,2
       )

array([[1., 0.]])

In [37]:
np.identity(1)

array([[1.]])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.ones(2)

array([1., 1.])

In [41]:
np.empty((1,1))

array([[1.]])

In [43]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.linspace(1,4,6,False)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [46]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])