<a href="https://colab.research.google.com/github/James-Arogo/Parrot/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np
import sys
import numpy as np

np.array([1,2,3,4,5,6,7]) # array in numpy


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
np.array([1,3,4,7,8,9],dtype='float32') #float datatype  or decimal numbers

array([1., 3., 4., 7., 8., 9.], dtype=float32)

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a)
a.shape #3 Dimensional array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [ ]:
a=np.array([
    [1,2,3],#indexing and slicing an array
    [4,5,6],
    [7,8,9],
    [0,1,6]
])
a[1]

array([4, 5, 6])

In [ ]:
a[1][0]

4

In [ ]:
a[1,0]

4

In [ ]:
a[0,2]

3

In [ ]:
a[:,2]

array([3, 6, 9, 6])

In [ ]:
a[2]=58

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [58, 58, 58],
       [ 0,  1,  6]])

In [ ]:
a[0,2]=58

In [ ]:
a

array([[ 1,  2, 58],
       [ 4,  5,  6],
       [58, 58, 58],
       [ 0,  1,  6]])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [ ]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a+10

array([10, 11, 12, 13])

In [ ]:
a+ 100

array([500, 501, 502, 503])

In [ ]:
a+=100
a

array([500, 501, 502, 503])

In [ ]:
a*10

array([5000, 5010, 5020, 5030])

In [ ]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])